### ISSUE TITLE
window not defined on LazyLoadService when deployed with Angular Universal

### ISSUE THREAD

**Issue by jsanta** [bob-lee/ng-notes#48]
Hi. I'm trying to deploy an Angular 8 app with Angular universal, and I'm getting the following error:
ReferenceError: window is not defined  at LazyLoadService.hasCompatibleBrowser

I could solve the same problem locally on my own code wrapping the window calls on a if(isPlatformBrowser(this.platformId)) if block. Tried to fix it myself but I got a little mixed up with your code.
Hope you can fix this great library. Thanks and best regards.

**Comment by bob-lee** [comment]
@jsanta just published `ng-lazy-load@1.0.8`, can you please try and advise if that helps?

**Comment by jsanta** [comment]
Works great! Thanks a lot.
